### ISSUE TITLE
The source of training and test

### ISSUE THREAD

**Issue by TrackingBird** [CVLAB-Unibo/Unsupervised-Adaptation-for-Deep-Stereo#1]
In the train.prototxt, why  the source for train and test are the same. Are they lmdb style?
    source: "/media/Dataset/Stereo_Conf/KITTI12_CCNN"
layer {
  name: "CustomData1"
  type: "CustomData"
  top: "blob0"
  top: "blob1"
  top: "blob2"
  top: "blobConfidence"
  include {
    phase: TRAIN
  }
  data_param {
    source: "/media/Dataset/Stereo_Conf/KITTI12_CCNN"
    batch_size: 4
    backend: LMDB
    rand_permute: false
    rand_permute_seed: 77
    slice_point: 3
    slice_point: 6
    slice_point: 7
    encoding: UINT8
    encoding: UINT8
    encoding: UINT16FLOW
    encoding: CONF
    verbose: true
  }
}
layer {
  name: "CustomData2"
  type: "CustomData"
  top: "blob0"
  top: "blob1"
  top: "blob2"
  top: "blobConfidence"
  include {
    phase: TEST
  }
  data_param {
    source: "/media/Dataset/Stereo_Conf/KITTI12_CCNN"
    batch_size: 1
    backend: LMDB
    rand_permute: false
    rand_permute_seed: 77
    slice_point: 3
    slice_point: 6
    slice_point: 7
    encoding: UINT8
    encoding: UINT8
    encoding: UINT16FLOW
    encoding: CONF
    verbose: true
  }
}

**Comment by AlessioTonioni** [comment]
Hi,
in this version of train.prototxt we use the same set of images both for train and test to display how our algorithm can successfully adapt to a new scenario without the need of real gt data (i.e. section 4.2 and table 1 in the paper). Any way you can use different train and test datasets just changing the corresponding paths. 

As for the format we use lmdb produced by the [convert_imageset_disparity_confidence_from_png.cpp](https://github.com/CVLAB-Unibo/Unsupervised-Adaptation-for-Deep-Stereo/blob/master/dispflownet-adaptation-release/tools/convert_imageset_disparity_confidence_from_png.cpp) tool.

**Comment by TrackingBird** [comment]
Hi AlessioTonion, thanks a lot for your reply, while in build caffe with "Unsupervised-Adaptation-for-Deep-Stereo" code.
```
"src/caffe/layers/l1loss_layer.cpp:28:5: error: ‘diff_bottom_vec_’ was not declared in this scope
     diff_bottom_vec_.clear();
     ^
src/caffe/layers/l1loss_layer.cpp:43:7: error: ‘dot_top_vec_’ was not declared in this scope
       dot_top_vec_.clear();
       ^
src/caffe/layers/l1loss_layer.cpp:44:31: error: ‘dot_’ was not declared in this scope
       dot_top_vec_.push_back(&dot_);
                               ^
src/caffe/layers/l1loss_layer.cpp:45:7: error: ‘dot_bottom_vec_’ was not declared in this scope
       dot_bottom_vec_.clear();
       ^
src/caffe/layers/l1loss_layer.cpp:50:7: error: ‘dot_layer_’ was not declared in this scope
       dot_layer_.reset(new EltwiseLayer<Dtype>(dot_param));
       ^
src/caffe/layers/l1loss_layer.cpp:53:7: error: ‘dot_top_vec_’ was not declared in this scope
       dot_top_vec_=diff_top_vec_;
       ^
src/caffe/layers/l1loss_layer.cpp:70:26: error: ‘dot_top_vec_’ was not declared in this scope
     square_layer_->SetUp(dot_top_vec_, square_top_vec_);
                          ^
src/caffe/layers/l1loss_layer.cpp: In member function ‘virtual void caffe::L1LossLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/l1loss_layer.cpp:103:34: error: ‘dot_top_vec_’ was not declared in this scope
     diff_layer_->Reshape(bottom, dot_top_vec_);
                                  ^
src/caffe/layers/l1loss_layer.cpp:115:28: error: ‘dot_top_vec_’ was not declared in this scope
     square_layer_->Reshape(dot_top_vec_, square_top_vec_);
                            ^
src/caffe/layers/l1loss_layer.cpp:44:31: error: ‘dot_’ was not declared in this scope
       dot_top_vec_.push_back(&dot_);
                               ^
src/caffe/layers/l1loss_layer.cpp:45:7: error: ‘dot_bottom_vec_’ was not declared in this scope
       dot_bottom_vec_.clear();
       ^
src/caffe/layers/l1loss_layer.cpp:50:7: error: ‘dot_layer_’ was not declared in this scope
       dot_layer_.reset(new EltwiseLayer<Dtype>(dot_param));
       ^
Makefile:576: recipe for target '.build_release/src/caffe/layers/l1loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/l1loss_layer.o] Error 1
make: *** 正在等待未完成的任务....
"
I think some declaration are missing from "/include/caffe/layers/l1_loss_layer.hpp". 
I added some declaration in l1_loss_layer.hpp, such as:
`vector<Blob<Dtype>*> diff_bottom_vec_;
vector<Blob<Dtype>*> dot_top_vec_;`
Can you please show me the declaration of other variables? Or can you show me the code of l1_loss_layer.hpp? Thanks a lots.

**Comment by TrackingBird** [comment]
Hi AlessioTonioni, Thanks a lot for your reply.  I am sorry, I still have some issues about  convert_imageset_disparity_confidence_from_png.cpp.
In this cpp, 
``std::string img1_filename;
    std::string img2_filename;
    std::string disp_filename;
    std::string conf_filename;
``

**Comment by TrackingBird** [comment]
Dear AlessioTonioni, Thanks for your reply. I have read your paper carefully. Can you please open AD-CENSUS and CCCN source code. I just want to test the perform of your algorithm on my dataset. However, I do not find the two source code on the internet. Sorry to bother you.
