### ISSUE TITLE
How to increase the variety of training set

### ISSUE THREAD

**Issue by TrackingBird** [CVLAB-Unibo/Unsupervised-Adaptation-for-Deep-Stereo#2]
Dear sir, sorry to bother you again. In your paper, you perform random data augmentation (color, brightness and contrast transformantions) as done by the authors of DispNets. However, I still wonder how to do that. For example, there are four images: left image **L** and right image **R**, disparity map **D** obtained by sgm, confidence map **C** obtained by CCCN.
Should we directly perform random data augmentation on **L**, **R** , **D** and **C** ?
Or should we perform random data augmentation on **L** and **R** to get more left and right images **L'** and **R'**？We get more disparity map and confidence map based on **L**' and **R'**？

Hope for your reply. Thanks.

**Comment by mattpoggi** [comment]
Hi, we perform random data augmentation on L and R as done by the authors of DispNet (in particular, the same intensity transformations are applied). This only changes image appearance, thus not introducing new disparity/confidence labels. This is already embedded into train.prototxt file.

Of course, you can augment disparity as well by introducing a random zoom factor on L, R, D and C (requiring to also scale D by the same factor) and horizontal translation vectors (summing the vector module to the disparity values), but this was not performed by the authors of DispNet and we maintained the same protocol.

**Comment by TrackingBird** [comment]
Thanks for your caffe model that I can see the performance of your method. Cvkit can be used to see pfm image. But I do not know how to convert pfm image into png. Can you help me. Thanks a lot

**Comment by AlessioTonioni** [comment]
A quick and dirty PFM to png conversion script:
https://pastebin.com/Z6JYYVJf
